soliloquy_web_get_movie:
    path: /movie/{title}
    defaults: { _controller: SoliloquyWebBundle:Movie:getMovie }
soliloquy_web_import_user_movies:
    path: /user/{username}/import
    defaults: { _controller: SoliloquyWebBundle:Movie:importUserMovies }
