services:
    soliloquy.provider.filmweb:
        class: Soliloquy\ProviderBundle\Provider\FilmwebProvider
        calls:
            - [setParser, ["@soliloquy.parser.filmweb"]]
            - [setMovieFactory, ["@soliloquy.movie.movie_factory"]]
            - [setDumpManager, ["@soliloquy.user.dump_manager"]]
