services:
    dom_parser:
        class: Sunra\PhpSimple\HtmlDomParser
    soliloquy.parser.filmweb:
        class: Soliloquy\ParserBundle\Parser\FilmwebParser
        arguments: [@dom_parser]
        calls:
            - [setMovie, ["@soliloquy.movie.movie"]]
